backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: "images"
public_folder: "/public"
collections:
  - name: "config"
    label: "Configuration du site"
    files:
      - name: "products"
        label: "Produits en vente"
        file: "/public/content/products.json"
        fields:
          - name: "title"
            label: "Titre à afficher"
            widget: "string"
          - name: "products1"
            label: "Produits (première colonne)"
            widget: "markdown"
          - name: "products2"
            label: "Produits (deuxième colonne)"
            widget: "markdown"
      - name: "openingHours"
        label: "horaires d'ouverture"
        file: "/public/content/openingHours.json"
        fields:
          - name: "monday"
            label: "Lundi"
            widget: "string"
          - name: "tuesday"
            label: "Mardi"
            widget: "string"
          - name: "wednesday"
            label: "Mercredi"
            widget: "string"
          - name: "thursday"
            label: "Jeudi"
            widget: "string"
          - name: "friday"
            label: "Vendredi"
            widget: "string"
          - name: "saturday"
            label: "Samedi"
            widget: "string"
          - name: "sunday"
            label: "Dimanche"
            widget: "string"
      - name: "warning"
        label: "Message important"
        file: "/public/content/warning.json"
        fields:
          - name: "isShown"
            label: "Afficher le message ?"
            widget: "boolean"
          - name: "title"
            label: "Titre du message"
            widget: "string"
          - name: "message"
            label: "Contenu du message"
            widget: "string"
      - name: "general"
        label: "Informations générales"
        file: "/public/content/general.json"
        fields:
          - name: "title"
            label: "Titre du site"
            widget: "string"
          - name: "subtitle"
            label: "Soustitre du site"
            widget: "text"
          - name: "presentation"
            label: "Présentation"
            widget: "text"
